name: Build Application with PyInstaller

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
      name: Check out the repository code

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: [DEBUG]Show customtkinter package details
      run: |
        pip show customtkinter

    - name: Build the executable with PyInstaller
      run: |
        pyinstaller --noconfirm --onedir --windowed --icon "./cmdcompass/static/icon.icns" --name "cmdCompass" \
        --add-data "./cmdcompass/data:data" \
        --add-data "./cmdcompass/static:static" \
        --add-data "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/customtkinter:customtkinter" \
        --collect-all "tkinterweb" \
        --distpath "./dist" \
        "./cmdcompass/main.py"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: executable
        path: dist/*
